source("codigos/lerDados")
source("codigos/rn")
source("codigos/amostragem")
source("codigos/tratamento")

cat("Criando modelo com RNA, com a base de treinamento 594 instâncias\n")
set.seed(14736941)
dados=random(titanic,1)
a=rna(dados)
a[[3]][which(a[[3]]==-1)]=0
prob_modelo=sum(a[[3]]==dados$trainigRotulo)/length(dados$trainigRotulo)
cat("\n\tModelo com acertivas de ",prob_modelo*100,"% da base de treinamento\n")
VP = sum(dados$testRotulo==1 & a[[3]]==1)
FP = sum(dados$testRotulo==1 & a[[3]]==0)
VN = sum(dados$testRotulo==0 & a[[3]]==0)
FN = sum(dados$testRotulo==0 & a[[3]]==1)
#Calculando a matriz Confusão para base de treinamento
M=matrix(c(VP,FN,FP,VN),nrow=2)
cat("Matriz de Confusão para base de treinamento\n")
colnames(M) <- c("+","-")
rownames(M) <-c("+","-")
print(M)

cat("Executando RNA, para os 297 primeiros casos de teste\n")
rot=teste(dados,a)
prob_modelo=sum(rot==dados$testRotulo)/length(rot)
cat("\tModelo com acertivas de ",prob_modelo*100,"% da base de teste\n")
VP = sum(dados$testRotulo==1 & rot==1)
FP = sum(dados$testRotulo==1 & rot==0)
VN = sum(dados$testRotulo==0 & rot==0)
FN = sum(dados$testRotulo==0 & rot==1)
#Calculando a matriz Confusão para base de treinamento
M=matrix(c(VP,FN,FP,VN),nrow=2)
cat("Matriz de Confusão para base de Teste\n")
colnames(M) <- c("+","-")
rownames(M) <-c("+","-")
print(M)
TFP_RNA=FP/(FP+VN)
TVP_RNA=VP/(VP+FN)
